### PR TITLE
Updated podspec to work on non static builds

### PR DESCRIPTION
**Pull request by TaylorDale**

### CODE REVIEW

**Review by MinaSamir11 — CHANGES_REQUESTED** [review]
Please can you mention or provide the error before fixing it or doc. to describe the change and to add in the release notes !?
Thank you in advance

**Comment by TaylorDale** [comment]
The dependency is React-Core not React and this caused it to break when
using use_frameworks! In the main podfile :)

**Review by MinaSamir11 — APPROVED** [review]

**Comment by jedashford** [comment]
@MinaSamir11 You may want to run a release with this change included. With .69.x this library build fails without this. Errors are not helpful: symbol(s) not found for architecture x86_64

With this change though, all works well

**Comment by MinaSamir11** [comment]
> @MinaSamir11 You may want to run a release with this change included. With .69.x this library build fails without this. Errors are not helpful: symbol(s) not found for architecture x86_64
> 
> With this change though, all works well

Will upload new release next days.

**Pull request merged**
