### PR TITLE
Update Play Core Library for Android 14 Compatibility

### PR DESCRIPTION
**Pull request by HarshitMadhav**
FIX: Android 14 compatibility issue https://github.com/MinaSamir11/react-native-in-app-review/issues/175

### CODE REVIEW

**Review by erickcrus — APPROVED** [review]
seems ok

**Comment by aadityapaliwal94** [comment]
Looks like this is not the correct way. In the migration they are saying - 

1. Remove any imports of the old Play Core libraries in your build.gradle file.
2. Integrate the Play In-App Review Library

```
// In your app’s build.gradle file:
...
dependencies {
    // This dependency is downloaded from the [Google’s Maven repository](https://developer.android.com/studio/build/dependencies#google-maven).
    // Make sure you also include that repository in your project's build.gradle file.
    implementation 'com.google.android.play:review:2.0.1'

    // For Kotlin users, also add the Kotlin extensions library for Play In-App Review:
    implementation 'com.google.android.play:review-ktx:2.0.1'
    ...
}
```

**Comment by MinaSamir11** [comment]
Please checkout and mention your installed version of in-app-review because it was fixed in the previous version. 

Thanks

**Comment by aadityapaliwal94** [comment]
@MinaSamir11 Yeah, it's fixed in the latest version.

**Comment by HarshitMadhav** [comment]
I was running on `^4.3.3v`

**Comment by HarshitMadhav** [comment]
@aadityapaliwal94 currently in the version 4.3.3 I can see this:
```
dependencies {
    implementation "com.google.android.play:review:${safeExtGet('playReviewVersion')}"
    implementation "com.google.android.gms:play-services-base:${safeExtGet('playServicesVersion')}"
}
```

which I think is correct as per your comment.

**Comment by MinaSamir11** [comment]
> @aadityapaliwal94 currently in the version 4.3.3 I can see this:
> 
> ```
> dependencies {
>     implementation "com.google.android.play:review:${safeExtGet('playReviewVersion')}"
>     implementation "com.google.android.gms:play-services-base:${safeExtGet('playServicesVersion')}"
> }
> ```
> 
> which I think is correct as per your comment.

exactly this is the latest version of the play review, no need to make any changes, till now.

**Comment by HarshitMadhav** [comment]
@MinaSamir11 but there is a mail from Google regarding the same to update the play core services for the android 14

**Comment by MinaSamir11** [comment]
may be another package implement play core

**Comment by HarshitMadhav** [comment]
@MinaSamir11 when I updated the play core for the package it worked fine, all I had to do was to update the play core version as shown in the PR

**Comment by MinaSamir11** [comment]
by the way, this property you updated didn't work with the project & will be removed next release version.

**Pull request closed without merging**
